Equipo102ProyectoUNLaM/trida

- front/src/containers/dashboards/contents.js
- front/src/data/contents.js
- front/src/data/evaluacion.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/contenidos/contenidos.js
- front/src/pages/app/evaluaciones/detalle-evaluacion/detalle-evaluacion.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/evaluaciones/index.js
Esta PR no tiene funcionalidad, solo el contexto en Evaluación y Contenidos.
> feature/DEV-119: se agrega contexto en evaluacion y contenidos

- front/src/pages/app/clases-virtuales/clases/form-clase.js
Test: 
- Crear una clase
- Fijarse en la DB de Firestore que se haya cargado el id de materia
> Feature/DEV-117: se añade id de materia al momento de crear la clase

- front/package.json
- front/src/components/videollamada/videollamada.js
- front/src/constants/defaultValues.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
Se agrega encripción de id de sala en base de datos. La encripción del password no se realizó ya que no se está guardando en la base de datos (evaluar si se realiza cuando encaremos la parte del alumno).
**Para probar:**
Crear una clase con videollamada y verificar que en la base de datos se guarde encriptada. Cuando se accede a la clase, en la tab videollamadas se debe mostrar desencriptada (uuid).
> feature/DEV-132: se agrega encripcion de id de sala en base de datos

- front/src/containers/navegacion/Topnav.js
- front/src/pages/app/clases-virtuales/clases/clases.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/contenidos/contenidos.js
- front/src/pages/app/evaluaciones/detalle-evaluacion/agregar-evaluacion.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/home/inicio.js
- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/practicas.js
- front/src/pages/course-selection/course.js
- front/src/pages/course-selection/institution.js
- front/src/redux/actions.js
- front/src/redux/institucion/actions.js
- front/src/redux/institucion/reducer.js
- front/src/redux/reducers.js
- front/src/redux/store.js
Se agrega Redux para curso, materia e institución, reemplazando al localStorage.
Se arregla funcionamiento de pagina de inicio, ahora permite cambiar de curso/materia/institución.
Para probar:
1- Cambiar curso, materia e institución en página de inicio y validar que en las demás secciones aparezcan los contenidos de la materia seleccionada.
2- Realizar una vuelta general en la aplicación ya que se cambio la forma de donde se toma la materia seleccionada.
> feature/DEV-136: se agrega redux para curso, materia e institucion

- front/cors.json
- front/src/App.js
- front/src/templates/email/action.js
- front/src/templates/email/recover-email.js
- front/src/templates/email/reset-password.js
- front/src/templates/email/verify-email.js
En esta PR se agrega la vista personalizada del link recibido cuando invitan a un usuario a una materia, y debe cambiar su contraseña. También se agregan dos vistas mas "recover-email" y "verify-email" que no aplican para esta PR, pero quizás sirva cuando utilicemos esa funcionalidad.
Para probar:
- Ingresar a una materia, e invitar a un usuario
- Ingresar al link recibido en el mail, y verificar que aparece la vista personalizada.
- Cambiar la contraseña, e ingresar con esa misma contraseña.
_NOTA: Cuando publiquemos, debemos cambiar la ruta de la url de los templates de firebase, para que sea trida.com.ar , ya que actualmente está localhost:3000 , por lo que para probarlo deberán tener corriendo el proyecto._
> Feature/dev 150 - Página personalizada al cambiar contraseña invitado

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/common/ColorSwitcher.js
Se cambia el texto y tamaño del color-switcher. Validar en login y en app.
> cambios en los textos del cambio de tema

- front/src/pages/app/clases-virtuales/clases/form-clase.js
Para validar, navegar a la modal de creación de clase y verificar que se marquen como requeridos los campos nombre, fecha y descripción.
> feature/DEV-202: se agregan validaciones en el form de clase utilizando react-hook-forms

- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/validations.js
En este PR se agregan las validaciones a la creación y edición de Prácticas.
**Para probar**
* Ir a la sección de Practicas.
* Crear una nueva práctica, checkear que todos los campos son obligatorios.
* Editar una práctica existente.
Notar que se sacó el campo duración, ya que no se le estaba dando utilidad.
> feature: DEV-201 - agregar validaciones a practicas

- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
Para probar, iniciar una videollamada exitosamente.
> se corrige bug en videollamada relacionado con nombre y apellido

- front/src/components/card-tabs.js
- front/src/constants/roles.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/evaluaciones/evaluaciones.js
En este **PR** se adapta la vista de evaluaciones para el alumno:
* Se remueve el botón de crear evaluación.
* Se sacan los botones de Editar y Eliminar evaluación.
* Se sacan los calendarios para cambiar la fecha de publicación y de finalización.
* Se saca la tab de Ejercicios.
* Se agrega un botón de Realizar evaluación. (Todavía no hace nada, hay una tarea para el realizar evaluación)
En un futuro se podría ver si es que queda una tab sola, como mostrarlo.
**Reviewer NO puede mergear**
> feature: DEV-165 - visualizar evaluaciones - Alumno

- front/src/helpers/Firebase-db.js
- front/src/helpers/Firebase-user.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
En este PR se agregan los mensajes generales en mis mensajes recibidos.
** Para probar: **
* Ingresar a mensajería con un docente, y enviar un mensaje general (puede ser con micaeladerito@gmail.com).
* Ingresar con otro usuario de esa material (laautaperez@gmail.com) y ver que aparece el mensaje general recibido.
> feature/DEV-210 - general message receive

- front/src/helpers/Firebase-db.js
Probar que cargue la pagina de inicio
> Se arreglan eventos de tipo evaluación

- front/src/assets/css/sass/_trida.style.scss
- front/src/handlers/DecryptionHandler.js
- front/src/handlers/EncryptionHandler.js
- front/src/helpers/Firebase-user.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/comunicaciones/mensajeria/validations.js
En este PR  se agrega:
- Validación por el campo "mensaje" (el texto o contenido del mismo) al enviar/responder un mensaje.
- Validación de que si no selecciona ningún recepetor, no habilita el botón _enviar_. 
- Se encripta el contenido del mensaje en la DB.
Para probar: 
-  Enviar, responder, reenviar mensajes. 
-  Verificar que todos los mensajes tienen su "contenido" encriptado en la DB, pero que se visualiza ok en Trida.
-  Verificar las validaciones mencionadas al principio. 
_Nota: Los usuarios disponibles para pobar son Mica y Lautarito, y creé uno nuevo como Alumno:_
_Mail: thomi.reynoso@hotmail.com_ 
_Pw: 123456_
> feature/dev 250: validación y encriptación de los mensajes

- front/src/components/card-tabs.js
- front/src/pages/app/evaluaciones/evaluaciones.js
En esta PR se agrega la funcionalidad de exportar una evaluación. Para probar:
- Como docente, navegar hasta evaluaciones
- Hacer click en exportar evaluacion
- Verificar que el archivo de texto descargado contenga el modelo de la BDD con los datos encriptados
> Feature/DEV-241 Exportar evaluación

- front/src/handlers/DecryptionHandler.js
- front/src/pages/app/evaluaciones/detalle-evaluacion/editar-evaluacion.js
- front/src/pages/app/evaluaciones/form-evaluacion.js
- front/src/pages/app/evaluaciones/realizar-evaluacion/realizar-evaluacion-confirmar.js
En esta PR se agregan las opciones de agregar características a las evaluaciones:
- No tomar capturas de pantalla
- No salir de la ventana
- Mensaje al alumno cuando se seleccionan alguna de estas características
Para probar:
- Crear una evaluación y seleccionar alguna de las opciones
- Editarla y verificar que aparezcan los datos cargados
- Entrar como alumno y verificar que se muestren los mensajes correspondientes.
NOTA: No incluye funcionalidades, solo son la carga de opciones
> Feature/dev 189 - características especiales en evaluación

- front/src/assets/css/sass/_trida.style.scss
- front/src/enumerators/tipoEjercicio.js
- front/src/handlers/DecryptionHandler.js
- front/src/handlers/EncryptionHandler.js
- front/src/pages/app/evaluaciones/detalle-evaluacion/vista-previa-evaluacion.js
- front/src/pages/app/evaluaciones/ejercicios/agregar-ejercicio.js
- front/src/pages/app/evaluaciones/ejercicios/preguntas_aleatorias.js
- front/src/pages/app/evaluaciones/realizar-evaluacion/realizar-evaluacion-confirmar.js
- front/src/pages/app/evaluaciones/realizar-evaluacion/realizar-evaluacion.js
En esta PR se agrega el componente de preguntas aleatorias en las evaluaciones
Para probar:
- Crear una evaluación con el tipo de ejercicio "Preguntas Aleatorias"
- Probar validaciones
- Probar editar
- Probar vista previa (Ya se cargarán la cantidad de preguntas indicadas de manera aleatoria, cada vez que se abra el modal, aparecerán preguntas distintas)
- Chequear que se guarde todo encriptado en firebase
- Ingresar como alumno y resolver la evaluación (Verificar que aparezcan la cantidad de preguntas establecidas en la evaluación de manera aleatoria)
- Probar validaciones
- Chequear que se guarde en correcciones con el tipo "evaluación"
> Feature/dev 280 - componente preguntas aleatorias

- front/src/components/landing/Contact.js
- front/src/containers/form-validations/FormikFields.js
- front/src/containers/pages/ModalEnviarInvitacion.js
- front/src/helpers/Firebase-db.js
- front/src/helpers/Firebase-storage.js
- front/src/helpers/Firebase-user.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/tabs-de-clase.js
- front/src/pages/app/clases-virtuales/clases/preguntas-clase/form-preguntas.js
- front/src/pages/app/contenidos/contenidos.js
- front/src/pages/app/contenidos/modal-audio.js
- front/src/pages/app/contenidos/modal-video.js
- front/src/pages/app/evaluaciones/form-evaluacion.js
- front/src/pages/course-selection/course.js
- front/src/pages/course-selection/institution.js
En esta pr se agregan notificaciones de error en caso de error.
> feature/DEV-220: se agregan notificaciones de error en caso de error

- front/src/assets/css/sass/_trida.style.scss
- front/src/containers/pages/ModalConfirmacion.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
Para probar ir a mensajería y abrir algún mensaje enviado o recibido para ver el detalle.
> feature/DEV-270: se cambian estilos de modal de detalle mensaje

- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
- front/src/pages/app/comunicaciones/foro/detalle-foro/input-mensaje-foro.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/contenidos/modal-audio.js
- front/src/pages/app/contenidos/modal-video.js
- front/src/pages/app/correcciones/correcciones.js
- front/src/pages/app/evaluaciones/ejercicios/opcion-multiple-imagen.js
- front/src/pages/app/evaluaciones/ejercicios/opcion-multiple.js
- front/src/pages/app/evaluaciones/ejercicios/oral.js
- front/src/pages/app/evaluaciones/ejercicios/respuesta-libre.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/evaluaciones/form-evaluacion.js
- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/form-subir-practica.js
- front/src/pages/app/practicas/practicas.js
- front/src/pages/course-selection/creacion/form-institucion.js
- front/src/pages/user/primer-login.js
En esta PR se remueve autocomplete de la mayoría de los inputs (menos los inputs email de login-registro).
> feature/DEV-279: se remueve autocomplete de la mayoría de los inputs

- front/src/assets/css/sass/_trida.style.scss
- front/src/pages/app/home/inicio.js
En esta PR se cambian de color los eventos del calendario de la home.
> feature/DEV-272: se cambian de color los eventos del calendario

- front/src/lang/locales/es_ES.js
- front/src/pages/app/clases-virtuales/clases/clases.js
- front/src/pages/app/comunicaciones/foro/foro.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/correcciones/correcciones.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/practicas/practicas.js
En este PR:
* Se modifican o agregan los mensajes que se muestran cuando no hay items.
* Se modifica el botón "Abrir pizarrón en otra ventana" para mantener el formato de todos los del header en mayúscula y los demas en capital letter.
* Ordenar las listas de mensajes
> feature/DEV-255: agregar estilos varios

- front/src/constants/errorMessages.js
Probar login con password invalido, el mensaje de error debe estar en español.
> feature/DEV-277: se agrega mensaje de error para password invalido

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/videollamada/videollamada.js
- front/src/helpers/Firebase-db.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/tabs-de-clase.js
En esta PR se agrega que el alumno pueda realizar preguntas anónimas durante la clase.
Para probar:
1- Conectarse a una clase como alumno y como docente.
2- Realizar una pregunta como alumno.
-> Se le debe mostrar el botón de 'Ver preguntas realizadas' tanto a alumno como a docente (si no hay preguntas, no se muestra).
3- Reaccionar a una pregunta como alumno al clickear el 👍 (se debe sumar un 1 a la pregunta, si clickea de nuevo se resta).
> feature/DEV-231: se agrega realización de preguntas de alumno en clase

- front/src/components/card-tabs.js
- front/src/components/videollamada/videollamada.js
- front/src/constants/adminArray.js
- front/src/constants/rolesData.js
- front/src/containers/navegacion/Footer.js
- front/src/containers/navegacion/Sidebar.js
- front/src/containers/pages/IconCards.js
- front/src/helpers/Firebase-db.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/admin/admin.js
- front/src/pages/app/admin/alumnos.js
- front/src/pages/app/admin/index.js
- front/src/pages/app/clases-virtuales/clases/clases.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/tabs-de-clase.js
- front/src/pages/app/comunicaciones/foro/foro.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/contenidos/contenidos.js
- front/src/pages/app/correcciones/correccion-imagen.js
- front/src/pages/app/correcciones/correccion-texto.js
- front/src/pages/app/correcciones/correcciones.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/index.js
- front/src/pages/app/practicas/practicas.js
- front/src/pages/course-selection/creacion/form-curso.js
- front/src/pages/course-selection/creacion/form-institucion.js
- front/src/pages/course-selection/creacion/form-materia.js
Validar que el directivo pueda realizar las mismas acciones que el docente
> Rol directivo: se cambian vistas agregando el rol directivo

- front/src/constants/ayuda/ayudaAlumno.js
- front/src/constants/ayuda/ayudaDirectivo.js
- front/src/constants/ayuda/ayudaDocente.js
- front/src/containers/navegacion/Footer.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/ayuda/ayuda.js
- front/src/pages/app/ayuda/index.js
- front/src/pages/app/index.js
En esta PR se agrega sección de ayuda para los 3 roles. Los textos cambian dependiendo del rol.
Por ahora no tenemos videos así que puse videos para perrear el fin de semana.
> feature/DEV-284: se agrega sección ayuda para los 3 roles

- front/src/components/landing/Contact.js
- front/src/containers/navegacion/Footer.js
- front/src/containers/pages/ModalContacto.js
- front/src/containers/pages/ModalPlanes.js
En esta PR se agrega modal para la sección de contacto.
Para probar, clickear el link 'Contacto' del footer y enviar un mensaje. Debe llegar a trida.app@gmail.com
> feature/DEV-307: se agrega modal para link de contacto

- front/src/assets/css/sass/_trida.style.scss
- front/src/pages/app/comunicaciones/foro/detalle-foro/detalle-foro.js
- front/src/pages/app/comunicaciones/foro/detalle-foro/detalle-mensaje.js
En este **PR** se agrega la funcionalidad de poder borrar mensajes del foro,
__Para probar:__
* Ir a un tema del foro como docente y borrar un mensaje.
* Ver que no se puede hacer como alumno.
> feature/DEV-312: borrar mensajes de foro

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/common/CountdownPreguntas.js
- front/src/constants/rolesData.js
- front/src/helpers/Firebase-db.js
- front/src/helpers/Firebase-user.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/ayuda/ayuda.js
- front/src/pages/app/comunicaciones/formales/form-formal.js
- front/src/pages/app/comunicaciones/formales/formales.js
- front/src/pages/app/comunicaciones/formales/tabs-de-formales.js
- front/src/pages/app/comunicaciones/formales/validations.js
Como directivo, navegar a Comunicaciones formales y probar de enviar una comunicación usando distintas opciones (docentes, alumnos, los dos). El mensaje debe llegar a los roles de la materia que haya seleccionado.
Usuarios para probar, todos en Inst Directiva - 2do - Lengua:
Directivo: trida.app@gmail.com
Docente: juli.foglia@gmail.com
Alumno: thomi.reynoso@hotmail.com
> feature/DEV-238: se agregan comunicaciones formales

- front/src/components/videollamada/videollamada.js
- front/src/constants/dropzoneValues.js
- front/src/constants/fileBrowser/confirmations/default.js
- front/src/constants/fileBrowser/confirmations/multiple.js
- front/src/helpers/Firebase-db.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/tabs-de-clase.js
- front/src/pages/app/clases-virtuales/clases/preguntas-clase/form-preguntas.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/contenidos/contenidos.js
- front/src/pages/app/evaluaciones/ejercicios/agregar-ejercicio.js
- front/src/pages/app/evaluaciones/ejercicios/opcion-multiple-imagen.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/evaluaciones/form-evaluacion-oral.js
- front/src/pages/app/evaluaciones/form-evaluacion.js
- front/src/pages/app/evaluaciones/realizar-evaluacion/realizar-evaluacion.js
- front/src/pages/app/practicas/practicas.js
- front/src/pages/user/primer-login.js
Se corrigen textos y alerta en creación de preguntas de clase.
> feature/DEV-282: se corrige alerta de preguntas y textos

- front/src/pages/app/evaluaciones/detalle-evaluacion/editar-evaluacion.js
- front/src/pages/app/evaluaciones/ejercicios/opcion-multiple.js
Validar que al borrar opciones multiples de una evaluación se eliminen las que se están borrando y no la última.
> bugfix/DEV-247: se arregla borrado de opcion multiple

- front/src/constants/texts.js
- front/src/containers/pages/ModalAsignacionMateria.js
- front/src/containers/pages/ModalEnviarInvitacion.js
Probar modal de invitacion y de asignacion de cursos como directivo. No hay mas tooltips, la informacion aparece toda en la modal.
> feature/DEV-316: se corrige informacion de modals invitar/asignar

- front/package-lock.json
- front/package.json
- front/src/assets/css/sass/_trida.style.scss
- front/src/constants/dropzoneValues.js
- front/src/helpers/Firebase.js
Probar que el mensaje del dropzone de mobile sea distinto al de desktop.
> Se agrega deteccion mobile y cambio de mensaje en contenidos

- front/src/assets/landing/css/style.scss
- front/src/constants/planes.js
- front/src/containers/navegacion/Footer.js
- front/src/containers/pages/ModalPlanes.js
- front/src/containers/pages/Planes.js
Probar abrir el modal de planes como inst publica (Inst Directiva), debe aparecer el mensaje diciendo que es gratis.
Probar abrir el modal de planes como inst privada (Pilar), debe aparecer el mensaje de prueba gratuita + planes de pago.
> feature/DEV-319: se agrega mas info a modal planes

- front/src/lang/locales/es_ES.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/modal-asociar-links.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/pagina-videollamada.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/comunicaciones/formales/form-formal.js
- front/src/pages/app/comunicaciones/foro/detalle-foro/input-mensaje-foro.js
- front/src/pages/app/comunicaciones/foro/form-foro.js
- front/src/pages/app/comunicaciones/foro/foro.js
- front/src/pages/app/comunicaciones/foro/validations.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/contenidos/modal-audio.js
- front/src/pages/app/contenidos/modal-video.js
- front/src/pages/app/evaluaciones/form-evaluacion-oral.js
- front/src/pages/app/evaluaciones/realizar-evaluacion-oral/pagina-videollamada.js
- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/form-subir-practica.js
- front/src/pages/course-selection/creacion/form-institucion.js
- front/src/pages/user/primer-login.js
En este **PR** se agrega la funcionalidad de crear, editar y borrar foros privados.
__Para probar:__
* Ingresar a Foros, ir a foros privados. (Con docente)
* Crear uno nuevo o editar uno viejo.
* Ver que el usuario actual (docente), no aparece en los integrantes a seleccionar, pero igual se agrega a los integrantes del foro.
* Ver que los foros se encuentran en la seccion correcta.
> feature: dev 311 - foros privados

- front/src/containers/navegacion/Sidebar.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/index.js
- front/src/pages/app/reportes/index.js
- front/src/pages/app/reportes/reportes-clases.js
- front/src/pages/app/reportes/reportes-evaluaciones.js
- front/src/pages/app/reportes/reportes-generales.js
- front/src/pages/app/reportes/reportes-practicas.js
Este **PR** agrega la navegación general a cada sección de reportes.
Para probar ver que se puede acceder a cada pagina de reporte solo con docente o directivo
> feature: dev 323 - navegacion general a reportes

- front/src/containers/navegacion/Footer.js
- front/src/containers/navegacion/Topnav.js
Probar que los links de Contacto y Ayuda en mobile aparezcan en el dropdown de la cuenta.
> feature/DEV-321: se agregan links de footer en mobile

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/videollamada/contestar-pregunta.js
- front/src/pages/app/clases-virtuales/clases/preguntas-clase/agregar-pregunta.js
- front/src/pages/app/clases-virtuales/clases/preguntas-clase/vista-previa-preguntas.js
- front/src/pages/app/evaluaciones/ejercicios/agregar-ejercicio.js
- front/src/pages/app/evaluaciones/ejercicios/opcion-multiple.js
Probar:
Preguntas de clase con dos tipos de opciones de respuesta
Evaluaciones: preguntas multiple choice no tendrian que tener cambios
> Feature/dev 313 - Preguntas de clase con respuestas unicas

- front/package-lock.json
- front/package.json
- front/src/assets/css/sass/_trida.style.scss
- front/src/lang/locales/es_ES.js
- front/src/pages/app/reportes/reportes-practicas.js
Navegar a la sección Reportes > Prácticas.
Debe aparecer el reporte de las prácticas entregadas por cada alumno (levanta de la colección 'correcciones').
> feature/DEV-325: se agrega reporte de prácticas

- front/src/pages/course-selection/creacion/form-materia.js
Para probar: registrarse y verificar que el usuario se haya añadido a usuariosPorInstitucion con su rol correspondiente
> Feature/DEV-302 - Se agrega a usuariosPorInstitucion en registo

- front/package-lock.json
- front/src/pages/app/reportes/reportes-evaluaciones.js
- front/src/pages/app/reportes/reportes-practicas.js
Navegar a la sección Reportes > Evaluaciones.
Debe aparecer el reporte de las evaluaciones entregadas por cada alumno (levanta de la colección 'correcciones').
*** Mergear después del 325!***
> feature/DEV-326: se agregan reportes de evaluaciones

- front/package-lock.json
- front/src/pages/app/reportes/reportes-evaluaciones.js
- front/src/pages/app/reportes/reportes-practicas.js
Reverts Equipo102ProyectoUNLaM/trida#155
> Revert "feature/DEV-326: se agregan reportes de evaluaciones"

- front/src/assets/css/sass/_trida.style.scss
- front/src/lang/locales/es_ES.js
- front/src/pages/app/evaluaciones/ejercicios/adjuntar-desarrollo.js
- front/src/pages/app/evaluaciones/realizar-evaluacion/realizar-evaluacion.js
Probar adjuntar varias imagenes en los ejercicios de adjuntar desarrollo:
- Ver bien la correccion
- Verificar url de las imagenes en firestore
- Ver bien el PDF generado
Yapa: no poder subir archivos pdf
> feature/DEV-334 - Adjuntar varias imagenes

- front/src/containers/form-validations/FormikFields.js
- front/src/containers/pages/DataListView.js
- front/src/helpers/Firebase-db.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/evaluaciones/form-evaluacion-oral.js
- front/src/pages/app/evaluaciones/form-evaluacion.js
- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/practicas.js
Probar creación, edición y filtros de prácticas para ver que funcione todo normalmente.
> feature/DEV-306: se cambian fechas de práctica a timestamp

- front/package-lock.json
- front/src/assets/css/sass/_trida.style.scss
- front/src/constants/emailTexts.js
- front/src/containers/navegacion/Topnav.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/cuenta/cuenta.js
- front/src/pages/app/cuenta/datos-form.js
- front/src/pages/app/cuenta/index.js
- front/src/pages/app/cuenta/password-form.js
- front/src/pages/app/cuenta/validations.js
- front/src/pages/app/index.js
En esta PR se agrega sección de mi cuenta.
Para probar, cambiar y actualizar los datos de cuenta. Si se realiza cambio de email va a llegar un mail tanto al mail viejo como al nuevo, avisando del cambio.
Probar de actualizar la contraseña, también debe llegar mail indicando el cambio.
> feature/DEV-332: se agrega sección de Mi Cuenta

- front/package-lock.json
- front/src/containers/navegacion/Topnav.Notifications.js
- front/src/pages/app/comunicaciones/formales/tabs-de-formales.js
- functions/index.js
En esta PR se agrega la funcionalidad de enviar notificaciones cuando se crea una evaluación oral y cuando se envía un comunicado formal.
Para probar:
- Loguearse como directivo y crear un comunicado. Verificar en el destinatario que llegue la notificación y al hacerle click redireccione e ilumine ese registro de la lista.
- Loguearse como docente y crear una evaluación oral. Verificar en los alumnos que llegue la notificación y al hacerle click redireccione e ilumine ese registro de la lista.
> Feature/dev 330 - notificaciones

- front/src/assets/css/sass/_trida.style.scss
- front/src/constants/messageTableColumns.js
- front/src/helpers/Firebase-db.js
- front/src/pages/app/comunicaciones/mensajeria/form-mensaje.js
- front/src/pages/app/comunicaciones/mensajeria/mensajeria.js
- front/src/pages/app/comunicaciones/mensajeria/tabs-de-mensajeria.js
En esta PR se agrega la funcionalidad de mostrar los mensajes como leídos y no leídos.
Para probar, enviar un mensaje a varios destinatarios y chequear que aparezcan como no leídos, y al abrirlos, cambien a leídos.
> Feature/dev 305 - mensajes no leídos

- front/src/pages/app/reportes/reportes-evaluaciones.js
- front/src/pages/app/reportes/reportes-practicas.js
Se agregan:
- Evaluaciones no entregadas en reporte de evaluaciones
- Fecha de finalización de evaluación en reporte de evaluaciones
- Fecha de vencimiento de práctica en reporte de prácticas
- Orden por fecha de finalización/fecha de vencimiento
> feature/DEV-340: se agregan evaluaciones no entregadas a reporte

- front/src/pages/app/evaluaciones/detalle-evaluacion/agregar-evaluacion.js
Para probar ir a evaluaciones e importar una. Validar que el input sea el del template y que cree bien la eval. También validar las extensiones que admite
> Se cambia input file en importar evaluaciones

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/lista-con-imagen.js
- front/src/components/videollamada/contestar-pregunta.js
- front/src/helpers/Firebase-db.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/comunicaciones/foro/form-foro.js
- front/src/pages/app/comunicaciones/foro/foro.js
- front/src/pages/user/primer-login.js
En este **PR** se agrega la posibilidad de agregar fotos a las clases y foros.
__Para probar:__
* Agregar una nueva clase cargandole una foto. (Ver que se carga correctamente en el storage)
* Editar una clase existente agregandole una foto.
* Hacer lo mismo con los foros
**Reviewer puede mergear**
> feature: DEV-341 - agregar foto a clase y foro

- front/package-lock.json
- front/src/assets/css/sass/_trida.style.scss
- front/src/components/videollamada/contestar-pregunta.js
- front/src/helpers/Firebase-db.js
- front/src/pages/app/clases-virtuales/clases/detalle-clase/respuestas-a-preguntas.js
En este PR se agrega un boton de actualizar a la tab de Respuestas, para que traiga las ultimas respuestas de los alumnos. 
Además, se agrega el insert a la nueva colección _respuestasPreguntasClase_ cuando un alumno responde una pregunta. Esto se hace para facilitar obtener los datos cuando se haga el reporte de preguntas de clase
Para probar: 
- Loguearse con alumno y profesor. Ir a la misma clase y lanzar pregunta.
- Con el alumno, responderla. 
- Con el docente, ir a la tab de respuestas y clickear en boton "actualizar"
- Verificar que al contestar una pregunta, las respuestas también se almacenan en la coleccion _respuestasPreguntasClase_
> feature:dev 320 - Se agrega boton actualizar a tab de Respuestas

- front/src/assets/css/sass/_trida.style.scss
- front/src/containers/navegacion/Sidebar.js
- front/src/containers/pages/DataListView.js
- front/src/containers/pages/ModalConfirmacion.js
- front/src/containers/pages/ModalVistaPlanilla.js
- front/src/lang/locales/es_ES.js
- front/src/pages/app/reportes/detalle-planilla.js
- front/src/pages/app/reportes/index.js
- front/src/pages/app/reportes/mi-planilla.js
- front/src/pages/app/reportes/mi-reporte.js
- front/src/pages/app/reportes/mis-planillas-guardadas.js
Se agrega guardado de planillas.
1- Navegar a Reportes - Mi planilla
2- Validar que al agregar columnas, los nombres de las mismas sean editables (son inputs).
3- Navegar a 'Ver planillas guardadas'
-> Se deben listar todas las planillas que el docente haya guardado, con opciones de abrir, previsualizar y borrar.
4- Al borrar se debe mostrar el modal de confirmación.
5- Al previsualizar se debe abrir un modal con la información de la planilla.
6- Al abrir, se debe abrir la planilla seleccionada.
En una planilla abierta, se debe poder editar o agregar columnas.
Al guardar una planilla abierta, se debe mostrar el modal de confirmación para validar si el docente quiere sobreescribir la planilla que abrió con los nuevos datos o guardar una nueva.
> feature/DEV-337: se agrega guardado de planillas

- front/src/pages/app/comunicaciones/foro/detalle-foro/detalle-foro.js
En este **PR** se agrega el escuchar en tiempo real los fotos
__Para probar:__
* Ingresar con dos usuarios (uno tiene que ser en incognito por ejemplo)
* Mandar un mensaje con uno y verlo al toque con el otro pues.
> feature: DEV-338 - escuchar mensajes en tiempo real del foro

- front/src/components/card-tabs-oral.js
- front/src/components/card-tabs.js
- front/src/containers/form-validations/FormikFields.js
Validar que en la selección de fechas en forms de Clases y Evaluaciones, los intervalos de horario sean de 15 minutos.
> feature/DEV-346: se cambian intervalos de calendario a 15 minutos

- front/src/pages/app/home/inicio.js
Se arregla que las notas se guarden en firestore solo si fueron modificadas (antes se guardaba si se abandonaba la pagina de inicio)
> Se arregla guardado de notas

- front/src/assets/css/sass/_trida.style.scss
- front/src/components/card-tabs.js
- front/src/constants/adminArray.js
- front/src/constants/menu.js
- front/src/containers/navegacion/Sidebar.js
- front/src/containers/pages/IconCards.js
- front/src/containers/pages/SubjectCardListView.js
- front/src/pages/app/admin/admin.js
- front/src/pages/app/admin/alumnos.js
- front/src/pages/app/clases-virtuales/clases/form-clase.js
- front/src/pages/app/comunicaciones/formales/tabs-de-formales.js
- front/src/pages/app/cuenta/datos-form.js
- front/src/pages/app/evaluaciones/evaluaciones.js
- front/src/pages/app/practicas/form-practica.js
- front/src/pages/app/practicas/practicas.js
- front/src/pages/course-selection/course.js
- front/src/pages/user/login.js
- front/src/pages/user/register.js
> Fixes generales

- functions/index.js
En esta PR se corrigen notificaciones de prácticas, foros privados, evaluaciones y correcciones.
Verificar:
- Que al crear una práctica, llegue al alumno la notificación.
- Que al corregir una práctica o evaluación, le llegue al alumno una notificación avisándole.
- Que al crear un foro privado, la notificación le llegue solo a los integrantes.
> corrección de prácticas + corrección de algunas notificaciones
